name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: sridher123/mytestrepo@v1.0/action.yml
        with:
          who-to-greet: VenkatramanB
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time}}"
